apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image
spec:
  params:
    - name: IMAGE
      type: string
    - name: GIT_REVISION
      type: string
      default: "master"
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      workingDir: /workspace/source/Prueba-CI_CD
      command:
        - /kaniko/executor
      args:
        - "--context=/workspace/source/Prueba-CI_CD"
        - "--dockerfile=/workspace/source/Prueba-CI_CD/Dockerfile"
        - "--destination=$(params.IMAGE)"
        - "--cache=true"
        - "--skip-tls-verify"
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      emptyDir: {}
