apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stepactions.tekton.dev
spec:
  group: tekton.dev
  names:
    kind: StepAction
    plural: stepactions
    singular: stepaction
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
  conversion:
    strategy: None
