apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-deploy-run
spec:
  pipelineRef:
    name: build-and-deploy-api
  serviceAccountName: tekton-pipeline-sa
  params:
    - name: IMAGE
      value: crygt/visits-api:latest  # Debe coincidir con la imagen esperada en Docker Hub
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: my-pvc
